addressbook/address_app/urls.py
from django.urls import include, path
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    path('', login_required(views.address_list), name='address_list'),
    path('new/', login_required(views.AddressCreateView.as_view()), name='address_create'),
    path('<int:pk>/edit', login_required(views.AddressUpdateView.as_view()), name='address_edit'),
    path('<int:pk>/delete', login_required(views.AddressDeleteView.as_view()), name='address_delete')
]

addressbook/addressbook/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('address_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

addressbook/address_app/models.py
from django.db import models
from django.contrib.auth.models import User
from localflavor.in_.models import INStateField

# Create your models here.

ADDRESS_TYPE_CHOICES = (
    ('home', 'Home'),
    ('work', 'Office/Commercial'),
)

class Address(models.Model):
    """Model class for Address"""
    user = models.ForeignKey(User, blank=False, null=False, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=512, help_text="Full name")
    address_first_line = models.CharField(max_length=512, help_text="Flat, House no., Building, Company, Apartment", null=False, blank=False)
    address_second_line = models.CharField(max_length=512, help_text="Area, Street, Sector, Village", null=True, blank=True)
    landmark = models.CharField(max_length=512, help_text="Landmark", null=True, blank=True)
    pincode = models.IntegerField(help_text="Pin code", null=False, blank=False)
    town_or_city = models.CharField(max_length=512, help_text="Town or City", null=True, blank=True)
    state = INStateField(help_text="State")
    address_type = models.CharField(max_length=10, choices=ADDRESS_TYPE_CHOICES, default='home')

addressbook/address_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from .models import Address

from django.views.generic.edit import CreateView, DeleteView, UpdateView

# Create your views here.

def address_list(request):
    address_list = Address.objects.filter(user=request.user)
    return render(request, 'address/address_list.html', {'address_list': address_list})


class AddressCreateView(CreateView):
    model = Address
    template_name = "address/address_form.html"
    fields = ('__all__')
    success_url = reverse_lazy('address_list')


class AddressUpdateView(UpdateView):
    model = Address
    template_name = "address/address_form.html"
    fields = ('__all__')
    success_url = reverse_lazy('address_list')


class AddressDeleteView(DeleteView):
    model = Address
    template_name = "address/address_confirm_delete.html"
    success_url = reverse_lazy('address_list')

addressbook/templates/address/address_confirm_delete.html
{% extends 'base.html' %}

{% block 'container'%}
 <h1 class="mt-5">Confirm delete</h1> 
 <p>Are you sure you want to delete this address?</p>
 <form method="post">
     {% csrf_token %}
     <input type="submit" class="btn btn-danger" value="Confirm">
     <a href="{% url 'address_list' %}" class="btn btn-info">No, take me back</a>
 </form>
{% endblock %}

addressbook/templates/address/address_form.html
{% extends 'base.html' %}

{% block 'container'%}
    {% if form.instance.pk %}
    <h1 class="mt-5">Edit address</h1> 
    {% else %}
    <h1 class="mt-5">Add new address</h1> 
    {% endif %}
    <form class="form-horizontal" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
                {% if field.name == 'user' %}
                <input type="hidden" name="user" value="{{ request.user.id }}">
                {% else %}
                    <div class="form-group">
                        {{ field.errors }}
                        {{ field.label_tag}} {{field }}
                    </div>
                {% endif %}
            {% endfor %}
        </fieldset>
        <a href="{% url 'address_list' %}" class="btn btn-danger">Cancel</a>
        <input type="submit" class="btn btn-info" value="Save">
    </form>    
{% endblock %}

addressbook/templates/address/address_list.html
{% extends 'base.html' %}

{% block 'container'%}
    <h1 class="mt-5">Hello {{ request.user.username }}! Manage your addresses <a href="{% url 'address_create' %}" class="btn btn-primary">Add</a></h1> 
    {% for address in address_list %}
        <div class="card">
            <div class="card-header">
            {{ address.full_name }}
            </div>
            <div class="card-body">
                <p class="card-text">
                    {{ address.address_first_line }} <br/>
                    {{ address.address_second_line|default:"" }} {% if address.address_second_line %} <br/> {% endif %}
                    {{ address.landmark|default:"" }} {% if address.landmark %} <br/> {% endif %}
                    {{ address.town_or_city|default:"" }}, {{ address.get_state_display }} <br/>
                    Pin code: {{ address.pincode }} <br/>
                    Address type: {{ address.get_address_type_display }}
                </p>
                <a href="{% url 'address_edit' pk=address.id %}" class="btn btn-info">Edit</a>
                <a href="{% url 'address_delete' pk=address.id %}" class="btn btn-danger">Delete</a>
            </div>
        </div>
        <br/>
        {% empty %}
            <p>No addresses found</p>        
    {% endfor %}
{% endblock %}

addressbook/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Address Book</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sticky-footer-navbar/">

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.0/examples/sticky-footer-navbar/sticky-footer-navbar.css" rel="stylesheet">
  </head>

  <body>

    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{% url 'address_list' %}">Address Book</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">
          <ul class="navbar-nav text-right">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>            
          </ul>
        </div>
      </nav>
    </header>

    <!-- Begin page content -->
    <main role="main" class="container">
      {% block 'container' %} {% endblock%}
    </main>

    <footer class="footer">
      <div class="container">
        <span class="text-muted">Copyright 2022</span>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="https://getbootstrap.com/docs/4.0/examples/sticky-footer-navbar/sticky-footer-navbar.css"></script>
    <script src="https://getbootstrap.com/docs/4.0/dist/js/bootstrap.min.js"></script>
  </body>
</html>